from PyQt5 import QtCore, QtGui, QtWidgets
from controller import *
from datetime import datetime
class rentalDetailsWindow(QtWidgets.QWidget):
    def __init__(self,brand, model, parent=None):
        print("opened window")
        super().__init__(parent)
        self.brand = brand
        self.model = model
        self.setObjectName("QtWidgets.QDialog")
        self.resize(400, 269)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.startDateBtn = QtWidgets.QPushButton(self.frame)
        self.startDateBtn.setMinimumSize(QtCore.QSize(130, 90))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons/calendar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startDateBtn.setIcon(icon)
        self.startDateBtn.setIconSize(QtCore.QSize(20, 20))
        self.startDateBtn.setObjectName("startDateBtn")
        self.verticalLayout_2.addWidget(self.startDateBtn)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.endDateBtn = QtWidgets.QPushButton(self.frame_2)
        self.endDateBtn.setMinimumSize(QtCore.QSize(130, 90))
        self.endDateBtn.setIcon(icon)
        self.endDateBtn.setIconSize(QtCore.QSize(20, 20))
        self.endDateBtn.setObjectName("endDateBtn")
        self.verticalLayout_3.addWidget(self.endDateBtn)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.rentCarBtn = QtWidgets.QPushButton(self.widget_2)
        self.rentCarBtn.setObjectName("rentCarBtn")
        self.horizontalLayout.addWidget(self.rentCarBtn)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("QtWidgets.QDialog", "QtWidgets.QDialog"))
        self.startDateBtn.setText(_translate("QtWidgets.QDialog", "Select start date"))
        self.label_3.setText(_translate("QtWidgets.QDialog", ""))
        self.endDateBtn.setText(_translate("QtWidgets.QDialog", "Select end date"))
        self.label_4.setText(_translate("QtWidgets.QDialog", ""))
        self.pushButton.setText(_translate("QtWidgets.QDialog", "Cancel"))
        self.rentCarBtn.setText(_translate("QtWidgets.QDialog", "Rent!"))

    def on_startDateBtn_pressed(self):
        self.calendar = QtWidgets.QCalendarWidget()
        self.calendar.clicked.connect(self.on_startDate_select)
        self.calendar.clicked.connect(self.calendar.close)
        self.calendar.show()
    def on_endDateBtn_pressed(self):
        self.calendar = QtWidgets.QCalendarWidget()
        self.calendar.clicked.connect(self.on_endDate_select)
        self.calendar.clicked.connect(self.calendar.close)
        self.calendar.show()
    def on_endDate_select(self, date):
        self.endDate = date.toString("dd.MM.yyyy")
        self.label_4.setText(date.toString("dd.MM.yyyy"))
    def on_startDate_select(self, date):
        self.startDate = date.toString("dd.MM.yyyy")
        self.label_3.setText(date.toString("dd.MM.yyyy"))
    def on_rentCarBtn_pressed(self):
        rent_a_car_transaction(datetime.strptime(self.startDate, '%d.%m.%Y'), datetime.strptime(self.endDate, '%d.%m.%Y'), self.brand, self.model)
        self.close()
    def on_pushButton_pressed(self):
        self.close()